// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns the engine version string.
String engineVersion() => RustLib.instance.api.crateApiEngineEngineVersion();

/// Returns the list of engine modules linked into this build.
List<String> listModules() => RustLib.instance.api.crateApiEngineListModules();

/// Returns a full health snapshot for the UI's engine-status view.
HealthReport healthCheck() => RustLib.instance.api.crateApiEngineHealthCheck();

/// A health snapshot the UI can render to confirm the engine is reachable.
class HealthReport {
  /// Always `true` when the engine responds; present so the UI has an explicit
  /// liveness flag rather than inferring it from a successful call.
  final bool ok;

  /// Engine version string.
  final String version;

  /// Names of the engine modules compiled into this build.
  final List<String> modules;

  const HealthReport({
    required this.ok,
    required this.version,
    required this.modules,
  });

  @override
  int get hashCode => ok.hashCode ^ version.hashCode ^ modules.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HealthReport &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          version == other.version &&
          modules == other.modules;
}
